---
title: Sample site for tech writers
baseURL: "/"
params:
  layout_style: overflow
  palette: blue
  header:
    title: Tech writer
    tagline: Built with Hugo
    profile_img: "/images/intro.jpg"
    bg: light
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
